# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: accfe4d
_src_path: gh:mlederbauer/copier-template
author_email: mlederbauer@ethz.ch
author_name: Magdalena Lederbauer
enforce_code_style: true
github_org: mlederbauer
package_name: glossagen
project_name: glossagen
short_description: creating a glossary out of schoalrly materials and chemistry reviews
